### ISSUE TITLE
bot admins within xmpp room

### ISSUE THREAD

**Issue by AquilaSagitta** [gbin/err#334]
Trying to set up bot admins in a jabber room. When you open a chat with someone in the room it uses address like: <code>room_name@domain/User</code>. The bot strips everything after the @ and thinks that the room name is the user name, thus the bot sees anyone in the room as an admin.

I tried looking through the source to see why this would be happening and how to fix it but I didn't see anything that would be causing it. Is there some way to tell the bot to use whatever's after the slash as user name?

edit: Looks like the issue lies with groupchat and chat type messages. A groupchat type message the user is properly extracted but when you private convo the bot it goes to chat type messages which extracts the room name as username

**Comment by Dafvid** [comment]
I'm looking at this issue too. It seems xmpp doesn't differentiate between "normal" private messages and "muc" private messages. They both have the type "chat". They are howevery treated rather differently. For admins I'd say it's better to use the bare JID of the user rather than the occupant JID of the MUC. 

For my own plugin I'm currently looking at comparing the JID from the muc private message to the channels the bot is currently in (that would be the name of the channel in the example above). If I have a match, I query the channel for a new Precense which should give me the full JID of the user.

In my opinion errbot should pass a MUCOccupant instead of a normal Identifier when the message is sent as a MUC private message.

**Comment by zoni** [comment]
I'm currently focused on getting the [Slack back-end](https://github.com/gbin/err/compare/slack) completed (which is at about 90% now), but once that is done I am going to investigate this issue and make sure it works as you would expect.

**Comment by gbin** [comment]
This should be better now on head, no more stripping and this allows private chat within chatrooms (and it is recognized as "chat"). We might improve it using MUCOccupants in the future.
