### ISSUE TITLE
HipChat HTML Support?

### ISSUE THREAD

**Issue by adamaflynn** [gbin/err#335]
What's the state of HTML support in the hipchat backend? It looks like they don't support XHTML-IM over XMPP (https://help.hipchat.com/forums/138883-suggestions/suggestions/2974079-support-xhtml-im-send-text-only-notifications-to), which seems to constrain the Err backend. 

But - is there any limited HTML support (even just bolding would be nice)? Any plans to move the backend to use the HipChat messaging API on the roadmap?

**Comment by gaahrdner** [comment]
FYI I can get XHTML-IM to work over HipChat, but only on 1-1 messages.  Room support does not seem to be supported as of now, but I'd invite everyone who wants this to happen to vote up the link @adamaflynn posted.

Here's a template I made that works as intended, note the lack of need to include `{% extends "base.html" %}` as is recommended in the wiki.

```python
{% block body %}
<p>
  <b>COME ON AND WORK MAN!</b>
</p>
{% endblock %}
```

**Comment by amorphic** [comment]
Re @adamaflynn's original post: it seems the Err's HipChat backend is completely broken at this stage.

Is a native HipChat plugin using the HipChat API the only real option to use HipChat for anything other than plain-text messaging?

**Comment by zoni** [comment]
@amorphic please open separate issues for any *"brokenness"* you experience with the HipChat back-end. I just opened a fix (#344) for one known issue but aside from this, there should be no problems with it.

@adamaflynn You're right that HipChat is rather limited in this area. We purposefully *do not* use the messaging API because it's unsuitable for sending large volumes of messages. My full reasoning for this can be found in the commit message of https://github.com/gbin/err/commit/aef572ab790e0510d247499087039b8f8bf185fd.

However the back-end does expose the notification end-point in a way that should be easy to use. If you have a room object, you can [.notify()](https://github.com/gbin/err/blob/master/errbot/backends/hipchat.py#L273-L286) it, and if you specify `format="html"` here you will get limited HTML support (limited by HipChat, not us).

**Comment by amorphic** [comment]
@zoni apologies - I didn't realise you'd tried the HipChat API and made a conscious decision to abandon it. Sadly I suspect that XHTML-IM support in HipChat might be quite a ways off...

So given that the HipChat backend just sends XHTML-IM anyway, is there any reason to use it over the standard XMPP backend?

**Comment by zoni** [comment]
No worries! And yes, I fear you may be right.

Yes, the HipChat back-end still has advantages over the plain XMPP one, mainly around MUC support. It can create and destroy MUC rooms and understands the difference between public and private ones, and it maps the human readable name to the JID so you can tell it to join the room *"Example room*" instead of having to specify *123456_example_room@conf.hipchat.com*.

It also lets you access the [hypchat](https://github.com/RidersDiscountCom/HypChat) client instance, so you can quite easily tap into the full HipChat API from your own plugins.

**Comment by gbin** [comment]
We should continue the discussion on #395 about the templating.
