### ISSUE TITLE
Python 2.7: You are missing configs defined from the template: Missing Config : absolute_config

### ISSUE THREAD

**Issue by ez47** [gbin/err#339]
I get this error when trying to run 
```scripts/err.py -T```

```
19:23:13 ERROR root You are missing configs defined from the template:
19:23:13 ERROR root Missing config : absolute_import
```

I have used python setup.py install for python 2.7. how do i fix this?

**Comment by sijis** [comment]
If you did python setup.py install, then err.py should be in your path.

I think that, as long as you have a config.py in the directory, you should be able to do  (no need to specify the script dir)
err.py -T

**Comment by ez47** [comment]
your correct, but doesnt really change anything.

**Comment by sijis** [comment]
What os and specific py2 version?

**Comment by ez47** [comment]
python 2.7.6 64-bit, Ubuntu 14.04 LTS 64bit

**Comment by l0bster** [comment]
same error here, using virtualenv with pip2.7
installation went fine bute cannot start the bot.

>(errbot)c-jui:errbot $ bin/err.py -H
>INFO:root:init plugin manager
>ERROR:root:You are missing configs defined from the template :
>ERROR:root:Missing config : absolute_import


Python 2.7.6, OS X Yosemite

**Comment by sijis** [comment]
confirmed. i'll see what's going on with that.

**Comment by l0bster** [comment]
thx :)

**Comment by zoni** [comment]
This is caused by `lib3to2` (which we use when installing under Python 2.7 to convert our Python 3 source-code to something Python 2.7 can handle) converting `config-template.py` and adding `from __future__ import absolute_import` to it. I'm not sure what's caused `3to2` to start doing this all of a sudden though.

I think the best thing to do is to exclude `config-template.py` from `3to2` conversion. This will also have the side-effect of not dropping all these unicode literals in front of all the strings, which makes it a bit nicer for users to read.

**Comment by zoni** [comment]
PR #345 should fix this issue. 

In the mean time, adding `from __future__ import absolute_import` to your own `config.py` should also allow the bot to start without error.
