### ISSUE TITLE
docs error

### ISSUE THREAD

**Issue by fmnisme** [gbin/err#428]
plugins in `BOT_EXTRA_PLUGIN_DIR` should have *.plug file,but your docs does not say it.

**Comment by zoni** [comment]
The plugin development docs already [explain](http://errbot.net/user_guide/plugin_development/basics/#plugin-metadata) about the `.plug` files.

Do you have a suggestion as to how to improve the documentation? How did you run into this? Did this happen because you downloaded a plugin from github somewhere and expected it to work by simply dropping it into `BOT_EXTRA_PLUGIN_DIR`, so you didn't read the plugin documentation because you weren't making your own plugin from scratch?

**Comment by fmnisme** [comment]
I see,Thank you!
